parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: camuma
    database_user: root
    database_password: clx4rpi
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 148410e3fb835f2e2b4eb6064265e471597f756c
    database_path: null
